.\" SPDX-FileCopyrightText: 2006 Istituto Nazionale di Fisica Nucleare
.\"
.\" SPDX-License-Identifier: Apache-2.0

'\" t
.\"     Title: voms-proxy-destroy
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.23
.\"      Date: 2025-04-09
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "VOMS\-PROXY\-DESTROY" "1" "2025-04-09" "\ \&" "\ \&"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
voms-proxy-destroy \- destroys a VOMS proxy
.SH "SYNOPSIS"
.sp
voms\-proxy\-destroy
.SH "DESCRIPTION"
.sp
The voms\-proxy\-destroy command is intended to be used after a proxy is no longer useful, to destroy it.
.SH "OPTIONS"
.sp
Options  may be specified indifferently with either a "\-" or "\-\-" prefix.
.sp
\fB\-h\fP, \fB\-help\fP Displays usage
.sp
\fB\-v\fP, \fB\-version\fP Displays version
.sp
\fB\-debug\fP Enables extra debug output
.sp
\fB\-q\fP, \fB\-\-quiet\fP Quiet mode, minimal output
.sp
\fB\-f\fP, \fB\-file\fP <proxyfile> The name of the file containing the proxy, in case it is in a non\-standard place.
.sp
\fB\-dry\fP Doesn\(cqt actually destroy the proxy.
.sp
\fB\-c\fP, \fB\-conf\fP <file> Read options from file.
.SH "BUGS"
.sp
.URL "https://savannah.cern.ch/bugs/?group=jra1mdw" "" ""
.SH "AUTHOR"
.sp
Enrico Vianello \c
.MTO "enrico.vianello\(atcnaf.infn.it" "" ""
.sp
Francesco Giacomini \c
.MTO "francesco.giacomini\(atcnaf.infn.it" "" ""
.SH "SEE ALSO"
.sp
voms\-proxy\-init(1), voms\-proxy\-info(1)