.\" SPDX-FileCopyrightText: 2006 Istituto Nazionale di Fisica Nucleare
.\"
.\" SPDX-License-Identifier: Apache-2.0

'\" t
.\"     Title: voms-proxy-init
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.23
.\"      Date: 2025-04-09
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "VOMS\-PROXY\-INIT" "1" "2025-04-09" "\ \&" "\ \&"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
voms-proxy-init \- creates a proxy certificate with VOMS extensions
.SH "SYNOPSIS"
.sp
\fBvoms\-proxy\-init\fP [options]
.SH "DESCRIPTION"
.sp
The voms\-proxy\-init command generates a proxy with the VOMS information included in an X.509 non critical extension.
.sp
The VOMS attributes are obtained from a known VOMS server. The list of known VOMS servers is configured using a \fBvomses\fP
configuration file, whose syntax is documented in the \fBvomses\fP man page. A custom vomses location can be specified using
the \fB\-\-vomses\fP option.
.sp
VOMS attributes are requested only if the \fB\-voms\fP option is passed on the command line, specifying for which
Virtual Organizations (VOs) attributes are requested.
.sp
VOMS attributes are signed by the VOMS server that issues them. The signature is verified on the client side leveraging
local trust information, which is typically maintained in
\fB/etc/grid\-security/vomsdir\fP. The vomsdir structure is documented in the \fBvomsdir\fP man page.
A custom vomsdir can be specified using the \fB\-\-vomsdir\fP option.
.sp
The default location of the proxy generated by voms\-proxy\-init is
.sp
.if n .RS 4
.nf
.fam C
 /tmp/x509up_u<user_id>
.fam
.fi
.if n .RE
.sp
where user_id is the effective user id of the user running the command.
A non\-standard location for the proxy can be specified using the \fB\-out\fP option.
.SS "Requesting VOMS attributes"
.sp
Attributes can be requested using the \fB\-voms\fP option. A basic usage is given in the following example:
.sp
.if n .RS 4
.nf
.fam C
voms\-proxy\-init \-voms <voname>
.fam
.fi
.if n .RE
.sp
where voname is the name of one of the configured VOs. The above command will create a proxy containing
a VOMS extension which holds all group attributes beloging to the user.
.sp
VOMS roles are conditional attributes which are included in a VOMS attribute certificate only when explicitly
requested. Roles can be requested using a command like the following one:
.sp
.if n .RS 4
.nf
.fam C
voms\-proxy\-init \-voms atlas:/atlas/Role=pilot
.fam
.fi
.if n .RE
.SS "Ordering requested attributes"
.sp
Typically VOMS attributes are returned in the order on which they are requested on the command line. For instance,
the following command:
.sp
.if n .RS 4
.nf
.fam C
voms\-proxy\-init \-voms infngrid:/infngrid/group1 \-voms infngrid:/infngrid/Role=pilot
.fam
.fi
.if n .RE
.sp
will produce an Attribute Certificate which has as the primary attribute \f(CR/infngrid/group1\fP, followed by \f(CR/infngrid/Role=pilot\fP,
and then by the other attributes belonging to the user. The \fB\-order\fP can also be used to express order requirements.
.SS "Setting the validity period of the generated proxy and attribute certificate"
.sp
By default, voms\-proxy\-init will generate a proxy valid for 12 hours including a VOMS extension valid for the same time (if requested).
These time periods can be changed using the \fB\-valid\fP option, which will set the validity of both the proxy and
the AC. Note that the validity of the AC can only be "proposed" by voms\-proxy\-init, as the AC validity is set by the VOMS server
and its maximum value is limited by local VOMS server configuration (typically the maximum value is 24 hours).
.SS "Setting the type of proxy generated by voms\-proxy\-init"
.sp
By default, voms\-proxy\-init generates a legacy proxy compatible with Globus Toolkit version 2. This behaviour can be changed using the \fB\-rfc\fP
option, which will produce an RFC3820 compliant proxy. In order to generate a Globus Toolkit version 3 proxy, i.e. a draft compliant proxy,
use the \fB\-proxyver 3\fP option.
.SH "CONFIGURATION"
.sp
Local configuration for trusted VOs is needed for \fIvoms\-proxy\-init\fP to work properly. See the \fIvomses(5)\fP and \fIvomsdir(5)\fP man pages
for more details.
.SH "OPTIONS"
.sp
Options  may be specified using either a "\-" or "\-\-" prefix.
.sp
\fB\-b,\-\-bits <num\-bits>\fP
.sp
.if n .RS 4
.nf
.fam C
Number of bits in key {512|1024|2048|4096}
.fam
.fi
.if n .RE
.sp
\fB\-\-cert <certfile>\fP
.sp
.if n .RS 4
.nf
.fam C
Nonstandard location of user certificate
.fam
.fi
.if n .RE
.sp
\fB\-\-certdir <certdir>\fP
.sp
.if n .RS 4
.nf
.fam C
Nonstandard location of trusted cert dir
.fam
.fi
.if n .RE
.sp
\fB\-\-conf <file>\fP
.sp
.if n .RS 4
.nf
.fam C
Read options from <file>
.fam
.fi
.if n .RE
.sp
\fB\-\-debug\fP
.sp
.if n .RS 4
.nf
.fam C
Enables extra debug output
.fam
.fi
.if n .RE
.sp
\fB\-\-dont_verify_ac\fP
.sp
.if n .RS 4
.nf
.fam C
Skips AC verification
.fam
.fi
.if n .RE
.sp
\fB\-f,\-\-failonwarn\fP
.sp
.if n .RS 4
.nf
.fam C
Treat warnings as errors
.fam
.fi
.if n .RE
.sp
\fB\-\-help\fP
.sp
.if n .RS 4
.nf
.fam C
Displays helps and exits
.fam
.fi
.if n .RE
.sp
\fB\-\-hours <hours>\fP
.sp
.if n .RS 4
.nf
.fam C
Sets the generated proxy validity to H hours (default:12).
Note that this option only sets the lifetime of the generated proxy.
Use \-valid to set lifetime for both the proxy and the AC.
.fam
.fi
.if n .RE
.sp
\fB\-\-ignorewarn\fP
.sp
.if n .RS 4
.nf
.fam C
Ignore warnings
.fam
.fi
.if n .RE
.sp
\fB\-k,\-\-key <keyfile>\fP
.sp
.if n .RS 4
.nf
.fam C
Non standard location of user key
.fam
.fi
.if n .RE
.sp
\fB\-\-limited\fP
.sp
.if n .RS 4
.nf
.fam C
Creates a limited proxy
.fam
.fi
.if n .RE
.sp
\fB\-n,\-\-noregen\fP
.sp
.if n .RS 4
.nf
.fam C
Use an existing proxy certificate to obtain VOMS attributes and to sign the new generated proxy
.fam
.fi
.if n .RE
.sp
\fB\-\-old\fP
.sp
.if n .RS 4
.nf
.fam C
Creates a legacy, GT2 compliant proxy (synonymous with \*(Aq\-proxyver 2\*(Aq)
.fam
.fi
.if n .RE
.sp
\fB\-\-order <fqan>\fP
.sp
.if n .RS 4
.nf
.fam C
The fqan specified with this option is set as the primary FQAN if present in the list of\&  attributes returned by the server.
Use this option more than once if you want to set the\&  order for more than one FQAN.
.fam
.fi
.if n .RE
.sp
\fB\-\-out <proxyfile>\fP
.sp
.if n .RS 4
.nf
.fam C
Non standard location of the generated proxy certificate
.fam
.fi
.if n .RE
.sp
\fB\-\-path_length <L>\fP
.sp
.if n .RS 4
.nf
.fam C
Allow a chain of at most L proxies to be generated and signed from the proxy created by voms\-proxy\-init.
.fam
.fi
.if n .RE
.sp
\fB\-\-proxyver <2|3|4>\fP
.sp
.if n .RS 4
.nf
.fam C
Sets the type of proxy generated by VOMS proxy init. 2 stands for legacy proxy,3 for draft proxy, 4 for rfc proxy.
Use \-old or \-rfc instead of this option.
.fam
.fi
.if n .RE
.sp
\fB\-\-pwstdin\fP
.sp
.if n .RS 4
.nf
.fam C
Reads private key passphrase from standard input.
.fam
.fi
.if n .RE
.sp
\fB\-q,\-\-quiet\fP
.sp
.if n .RS 4
.nf
.fam C
Quiet mode, minimal output
.fam
.fi
.if n .RE
.sp
\fB\-r,\-\-rfc\fP
.sp
.if n .RS 4
.nf
.fam C
Creates an RFC 3820 compliant proxy (synonymous with \*(Aq\-proxyver 4\*(Aq)
.fam
.fi
.if n .RE
.sp
\fB\-\-target <hostname>\fP
.sp
.if n .RS 4
.nf
.fam C
Targets the AC against a specific hostname. Multiple targets can be expressed using this option multiple times.
.fam
.fi
.if n .RE
.sp
\fB\-\-usage\fP
.sp
.if n .RS 4
.nf
.fam C
Displays helps and exits
.fam
.fi
.if n .RE
.sp
\fB\-\-valid <h:m>\fP
.sp
.if n .RS 4
.nf
.fam C
Sets generated proxy and AC validity to h hours and m minutes (defaults to 12:00).
Note that the VOMS server could shorten the validity of the issued AC depending on the server configuration.
.fam
.fi
.if n .RE
.sp
\fB\-\-verify\fP
.sp
.if n .RS 4
.nf
.fam C
Verifies the validity of the user certificate.
.fam
.fi
.if n .RE
.sp
\fB\-\-version\fP
.sp
.if n .RS 4
.nf
.fam C
Displays version
.fam
.fi
.if n .RE
.sp
\fB\-\-voms <voms<:fqan>>\fP
.sp
.if n .RS 4
.nf
.fam C
Specifies the VO for which the AC is requested. <:fqan> is optional,and is used to ask for
specific attributes (e.g:\&  \-\-voms atlas:/atlas/Role=pilot).
This option can be used multiple times to request multiple FQANs for different VOs.
The order in which the option appears on the command line influence the order of the issued attributes.
.fam
.fi
.if n .RE
.sp
\fB\-\-vomsdir <DIR>\fP
.sp
.if n .RS 4
.nf
.fam C
Sets the path where lsc files and other local VOMS trust anchors will be looked for.
.fam
.fi
.if n .RE
.sp
\fB\-\-vomses <vomses file>\fP
.sp
.if n .RS 4
.nf
.fam C
Specifies the name of a VOMSES file from which VOMS server contact information is parsed.
.fam
.fi
.if n .RE
.sp
\fB\-\-vomslife <h:m>\fP
.sp
.if n .RS 4
.nf
.fam C
Sets the validity of the requested VOMS attribute certificate to h hours and m minutes (defaults to the value of the \*(Aq\-valid\*(Aq option)
.fam
.fi
.if n .RE
.SH "BUGS"
.sp
To report bugs or ask for support, use GGUS: \c
.URL "https://ggus.eu/pages/home.php" "" ""
.SH "AUTHORS"
.sp
Enrico Vianello \c
.MTO "enrico.vianello\(atcnaf.infn.it" "" ""
.sp
Francesco Giacomini \c
.MTO "francesco.giacomini\(atcnaf.infn.it" "" ""
.SH "SEE ALSO"
.sp
voms\-proxy\-destroy(1), voms\-proxy\-info(1), vomses(5), vomsdir(5)