.\" SPDX-FileCopyrightText: 2006 Istituto Nazionale di Fisica Nucleare
.\"
.\" SPDX-License-Identifier: Apache-2.0

'\" t
.\"     Title: vomses
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.23
.\"      Date: 2025-04-09
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "VOMSES" "5" "2025-04-09" "\ \&" "\ \&"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
vomses \- The VOMS server contact table
.SH "SYNOPSIS"
.sp
\fB/etc/vomses\fP
.sp
\fB~/.glite/vomses\fP
.SH "DESCRIPTION"
.sp
This manual page describes the format of \fIvomses\fP files.
\fIvomses\fP files contain contact information for VOMS servers and are typically organized in the \fB/etc/vomses\fP directory.
A \fIvomses\fP file is a simple text file which contains one or more lines formatted as follows:
.sp
"alias" "hostname" "port" "server DN" "vo_name"
.sp
Where:
.sp
\fBalias\fP: an alias that can be used for this VOMS server (this is typically identical to the vo_name)
.sp
\fBhostname\fP: the hostname where the VOMS server is running
.sp
\fBvo_name\fP: the name of the VO served by the VOMS server
.sp
\fBport\fP: the port where the VOMS server is listening for incoming requests
.sp
\fBserver DN\fP: the certificate subject of the VOMS server
.sp
System wide VOMSES configuration is maintained in the \fB/etc/vomses\fP file or directory.
If \fB/etc/vomses\fP is a directory, all the files contained in such directory are parsed looking for VOMS
contact information.
.sp
A user can define its custom \fBvomses\fP configuration in the \fB~/.glite/vomses\fP file or directory, which
will be parsed in the same way as just described.
.SH "EXAMPLES"
.sp
The following is an example of valid vomes file for the \fBcms\fP VO:
.sp
.if n .RS 4
.nf
.fam C
"cms" "lcg\-voms.cern.ch" "15002" "/DC=ch/DC=cern/OU=computers/CN=lcg\-voms.cern.ch" "cms"
"cms" "voms.cern.ch" "15002" "/DC=ch/DC=cern/OU=computers/CN=voms.cern.ch" "cms"
.fam
.fi
.if n .RE
.SH "BUGS"
.sp
To report bugs or ask for support, use GGUS: \c
.URL "https://ggus.eu/pages/home.php" "" ""
.SH "AUTHORS"
.sp
Enrico Vianello \c
.MTO "enrico.vianello\(atcnaf.infn.it" "" ""
.sp
Francesco Giacomini \c
.MTO "francesco.giacomini\(atcnaf.infn.it" "" ""
.SH "SEE ALSO"
.sp
voms\-proxy\-destroy(1), voms\-proxy\-info(1), vomsdir(5)